---
apiVersion: v1
kind: Namespace
metadata:
  name: openlookeng
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openlookeng-catalogs
  namespace: openlookeng
data:
  mysql.properties: |
    connector.name=mysql
    connection-url=mariadb-svc.mariadb.svc.cluster.local:3306
    connection-user=openeulersummit
    connection-password=vlTrlL90k
---
apiVersion: v1
kind: Service
metadata:
  name: openlookeng-server
  namespace: openlookeng
spec:
  selector:
    app: openlookeng-server
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    name: openlookeng
---
apiVersion: v1
kind: Pod
metadata:
  name: openlookeng-server
  namespace: openlookeng
  labels:
    app: openlookeng-server
spec:
  nodeSelector:
    kubernetes.io/arch: arm64
  containers:
    - name: openlookeng-server
      image: ghcr.io/zhengzhenyu/openlookeng-arm:with_ui
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
        name: openlookeng
      volumeMounts:
        - name: mysql-connector
          mountPath: /home/openlkadmin/hetu-server/catalog/mysql.properties
          subPath: mysql.properties
      env:
        - name: IS_COORDINATOR
          value: "True"
        - name: INCLUDE_COORDINATOR
          value: "True"
        - name: HTTP_PORT
          value: "8080"
        - name: DISCOVERY_URI
          value: "http://localhost:8080"
        - name: NODE_ENVIRONMENT
          value: "openeulersummit"
  volumes:
    -name: mysql-config
      configMap:
        name: openlookeng-catalogs
        items:
          - key: mysql.properties
            path: mysql.properties
  restartPolicy: Always
