---
apiVersion: v1
kind: Namespace
metadata:
  name: openlookeng
---
apiVersion: v1
kind: Service
metadata:
  name: openlookeng-server
  namespace: openlookeng
spec:
  selector:
    app: openlookeng-server
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    name: openlookeng
---
apiVersion: v1
kind: Pod
metadata:
  name: openlookeng-server
  namespace: openlookeng
  labels:
    app: openlookeng-server
spec:
  nodeSelector:
    kubernetes.io/arch: arm64
  containers:
    - name: openlookeng-server
      image: ghcr.io/zhengzhenyu/openlookeng-arm:with_ui
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
        name: openlookeng
      env:
        - name: IS_COORDINATOR
          value: "True"
        - name: INCLUDE_COORDINATOR
          value: "True"
        - name: HTTP_PORT
          value: "8080"
        - name: DISCOVERY_URI
          value: "http://localhost:8080"
        - name: NODE_ENVIRONMENT
          value: "openeulersummit"
  restartPolicy: Always
