---
apiVersion: v1
kind: Namespace
metadata:
  name: openlookeng
---
apiVersion: v1
kind: Service
metadata:
  name: openlookeng-frontend
  namespace: openlookeng
spec:
  selector:
    app: openlookeng-frontend
  ports:
  - name: airpal
    port: 8081
    targetPort: 8081
    nodePort: 8081
    protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: openlookeng-frontend
  namespace: openlookeng
  labels:
    app: openlookeng-frontend
spec:
  nodeSelector:
    kubernetes.io/arch: amd64
  containers:
    - name: openlookeng-frontend
      image: ghcr.io/zhengzhenyu/airpal-ubuntu:latest
      imagePullPolicy: Always
      env:
        - name: MYSQL_HOST
          value: "114.119.184.236"
        - name: PRESTO_SERVER_URI
          value: "http://119.8.114.27:8090"
  restartPolicy: Always
