---
apiVersion: v1
kind: Namespace
metadata:
  name: openlookeng
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openlookeng-catalogs
  namespace: openlookeng
data:
  opengauss.properties: |
    connector.name=postgresql
    connection-url=jdbc:postgresql://opengauss.db-opengauss-singleton.svc.cluster.local:5432/postgres
    connection-user=gaussdb
    connection-password=rxcwcbwi43SXwqr@
  mariadb.properties: |
    connector.name=mysql
    connection-url=jdbc:mysql://mariadb-svc.mariadb.svc.cluster.local:3306
    connection-user=openeulersummit
    connection-password=vlTrlL90k
---
apiVersion: v1
kind: Service
metadata:
  name: openlookeng-server
  namespace: openlookeng
spec:
  selector:
    app: openlookeng-server
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    name: openlookeng
---
apiVersion: v1
kind: Pod
metadata:
  name: openlookeng-server
  namespace: openlookeng
  labels:
    app: openlookeng-server
spec:
  nodeSelector:
    kubernetes.io/arch: arm64
  containers:
    - name: openlookeng-server
      image: ghcr.io/zhengzhenyu/openlookeng-arm:with_ui
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
        name: openlookeng
      volumeMounts:
        - name: gauss-config
          mountPath: /home/openlkadmin/hetu-server/etc/catalog/opengauss.properties
          subPath: opengauss.properties
        - name: mariadb-config
          mountPath: /home/openlkadmin/hetu-server/etc/catalog/mariadb.properties
          subPath: mariadb.properties
      env:
        - name: IS_COORDINATOR
          value: "True"
        - name: INCLUDE_COORDINATOR
          value: "True"
        - name: HTTP_PORT
          value: "8080"
        - name: DISCOVERY_URI
          value: "http://localhost:8080"
        - name: NODE_ENVIRONMENT
          value: "openeulersummit"
  volumes:
    - name: gauss-config
      configMap:
        name: openlookeng-catalogs
    - name: mariadb-config
      configMap:
        name: openlookeng-catalogs
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: openlookeng-worker-arm
  namespace: openlookeng
spec:
  selector:
    app: openlookeng-worker-arm
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    name: openlookeng-worker-arm
---
apiVersion: v1
kind: Pod
metadata:
  name: openlookeng-worker-arm
  namespace: openlookeng
  labels:
    app: openlookeng-worker-arm
spec:
  nodeSelector:
    kubernetes.io/arch: arm64
  containers:
    - name: openlookeng-worker-arm
      image: ghcr.io/zhengzhenyu/openlookeng-arm:with_ui
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
        name: openlookeng-worker-arm
      volumeMounts:
        - name: gauss-config
          mountPath: /home/openlkadmin/hetu-server/etc/catalog/opengauss.properties
          subPath: opengauss.properties
        - name: mariadb-config
          mountPath: /home/openlkadmin/hetu-server/etc/catalog/mariadb.properties
          subPath: mariadb.properties
      env:
        - name: HTTP_PORT
          value: "8080"
        - name: DISCOVERY_URI
          value: "http://openlookeng-server.openlookeng.svc.cluster.local:8080"
        - name: NODE_ENVIRONMENT
          value: "openeulersummit"
  volumes:
    - name: gauss-config
      configMap:
        name: openlookeng-catalogs
    - name: mariadb-config
      configMap:
        name: openlookeng-catalogs
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: openlookeng-worker-x86
  namespace: openlookeng
spec:
  selector:
    app: openlookeng-worker-x86
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    name: openlookeng-worker-x86
---
apiVersion: v1
kind: Pod
metadata:
  name: openlookeng-worker-x86
  namespace: openlookeng
  labels:
    app: openlookeng-worker-x86
spec:
  nodeSelector:
    kubernetes.io/arch: amd64
  containers:
    - name: openlookeng-worker-x86
      image: ghcr.io/zhengzhenyu/openlookeng-x86:with_ui
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
        name: openlookeng-worker-x86
      volumeMounts:
        - name: gauss-config
          mountPath: /home/openlkadmin/hetu-server/etc/catalog/opengauss.properties
          subPath: opengauss.properties
        - name: mariadb-config
          mountPath: /home/openlkadmin/hetu-server/etc/catalog/mariadb.properties
          subPath: mariadb.properties
      env:
        - name: HTTP_PORT
          value: "8080"
        - name: DISCOVERY_URI
          value: "http://openlookeng-server.openlookeng.svc.cluster.local:8080"
        - name: NODE_ENVIRONMENT
          value: "openeulersummit"
  volumes:
    - name: gauss-config
      configMap:
        name: openlookeng-catalogs
    - name: mariadb-config
      configMap:
        name: openlookeng-catalogs
  restartPolicy: Always
